// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGlOLixeDV0DiLecUqJBmf4PEYVvOmSVg',
    appId: '1:273719108763:android:c48644c97c6cf6c7d6523e',
    messagingSenderId: '273719108763',
    projectId: 'react-ff62a',
    storageBucket: 'react-ff62a.firebasestorage.app',
    databaseURL: 'https://react-ff62a-default-rtdb.europe-west1.firebasedatabase.app', // Realtime DB URL
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1GYhUO0p68nIKN6W4np493h5aYcuUU3U',
    appId: '1:273719108763:ios:38fbd94132683782d6523e',
    messagingSenderId: '273719108763',
    projectId: 'react-ff62a',
    storageBucket: 'react-ff62a.firebasestorage.app',
    iosBundleId: 'com.example.offroadNav',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1GYhUO0p68nIKN6W4np493h5aYcuUU3U',
    appId: '1:273719108763:ios:38fbd94132683782d6523e',
    messagingSenderId: '273719108763',
    projectId: 'react-ff62a',
    storageBucket: 'react-ff62a.firebasestorage.app',
    iosBundleId: 'com.example.offroadNav',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHg8yCZ-2JUM32JndVTeAWGFhZXzrSvnQ',
    appId: '1:273719108763:web:f26b7dee600a8accd6523e',
    messagingSenderId: '273719108763',
    projectId: 'react-ff62a',
    authDomain: 'react-ff62a.firebaseapp.com',
    storageBucket: 'react-ff62a.firebasestorage.app',
    measurementId: 'G-QPB0D454T3',
  );
}
